In [14]:
import pandas as pd, numpy as np

In [58]:
b = [0,1,2,3,4,5,666]
b.remove(666)
print(b)
b.pop(-2)
print(b)

b.pop(0)
print(b)


[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 5]
[1, 2, 3, 5]


In [15]:
array1 = np.arange(3,10,3)
print(array1)

[3 6 9]


In [16]:
print(np.power(array1,3))
print(array1**4)

[ 27 216 729]
[  81 1296 6561]


In [17]:
conditional_filter = array1 < 5
print(conditional_filter)
print(array1[conditional_filter])

[ True False False]
[3]


In [18]:
# matrix multiplication
array2 = np.array([[3,5],[2,4]])
array3 = np.array([[1,2],[30,40]])
array2 @ array3

array([[153, 206],
       [122, 164]])

In [19]:
array2.dot(array3)

array([[153, 206],
       [122, 164]])

In [20]:
random_array = np.random.random((3,2))
print(random_array)
print(random_array.min())
print(random_array.sum())
print(random_array.sum(axis=0)) ##column wise ekle

[[0.73884503 0.3150557 ]
 [0.60473329 0.44442589]
 [0.93576294 0.76831241]]
0.3150557049159123
3.807135256991103
[2.27934125 1.52779401]


In [21]:
help(np.triu)

Help on function triu in module numpy:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of an array with the elements below the `k`-th diagonal
    zeroed.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])



In [22]:
a = np.ones((3,4), dtype=np.int8)
print(a)
a = a*200
print(a)
a = a*200
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[200 200 200 200]
 [200 200 200 200]
 [200 200 200 200]]
[[-25536 -25536 -25536 -25536]
 [-25536 -25536 -25536 -25536]
 [-25536 -25536 -25536 -25536]]


In [23]:
a=np.array(np.arange(20))
a = a.reshape(5,4)
print(a)
a.resize(10,2)
print(a)
a.resize(5,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [24]:
b = np.array([3,2])
print(b)
a.resize(10,2)
a + b

[3 2]


array([[ 3,  3],
       [ 5,  5],
       [ 7,  7],
       [ 9,  9],
       [11, 11],
       [13, 13],
       [15, 15],
       [17, 17],
       [19, 19],
       [21, 21]])

In [25]:
my_list = [10,20,30]
print(my_list*2)
mapobj = map(lambda x: 3*x, my_list)
print(mapobj)
print(list(mapobj))

[10, 20, 30, 10, 20, 30]
[30, 60, 90]


In [26]:
# create dataframe with 3 columns
data = pd.DataFrame({
    "column1": [12, 23, 45, 67],
    "column2": [67, 54, 32, 1],
    "column3": [34, 23, 56, 23]
}
)
# get correlation between element wise
correlation_matrix = data.corr()
print(correlation_matrix)
print(type(correlation_matrix))

              column1   column2       column3
column1  1.000000e+00 -0.997048  4.993708e-17
column2 -9.970477e-01  1.000000  7.347000e-02
column3  4.993708e-17  0.073470  1.000000e+00
<class 'pandas.core.frame.DataFrame'>


In [27]:
print(correlation_matrix.abs())
print('\n {} \n'.format('hehe'*3))
print(correlation_matrix.abs().unstack())

              column1   column2       column3
column1  1.000000e+00  0.997048  4.993708e-17
column2  9.970477e-01  1.000000  7.347000e-02
column3  4.993708e-17  0.073470  1.000000e+00

 hehehehehehe 

column1  column1    1.000000e+00
         column2    9.970477e-01
         column3    4.993708e-17
column2  column1    9.970477e-01
         column2    1.000000e+00
         column3    7.347000e-02
column3  column1    4.993708e-17
         column2    7.347000e-02
         column3    1.000000e+00
dtype: float64


In [28]:
manipulated_corr = correlation_matrix.replace(to_replace=1,value=0)
print(manipulated_corr)
print(manipulated_corr.max())

              column1   column2       column3
column1  0.000000e+00 -0.997048  4.993708e-17
column2 -9.970477e-01  0.000000  7.347000e-02
column3  4.993708e-17  0.073470  0.000000e+00
column1    4.993708e-17
column2    7.347000e-02
column3    7.347000e-02
dtype: float64


In [29]:
unstacked = manipulated_corr.abs().unstack()
print(type(unstacked))
print(unstacked)
print(unstacked.max())
print(unstacked.idxmax())

<class 'pandas.core.series.Series'>
column1  column1    0.000000e+00
         column2    9.970477e-01
         column3    4.993708e-17
column2  column1    9.970477e-01
         column2    0.000000e+00
         column3    7.347000e-02
column3  column1    4.993708e-17
         column2    7.347000e-02
         column3    0.000000e+00
dtype: float64
0.9970476685163736
('column1', 'column2')


In [30]:
my_list2 = range(31)
arr3 = np.array(my_list2)
print(arr3.nbytes)

124


## ELEMAN BAZLI CALISIYOR DIZI BAZLI DEGIL, ICINDE SERI BILE OLSA 
np.full np.repeat'in tersi, liste olursa unique'leri alır.


In [31]:
print(np.zeros)
print(np.ones)
print(np.repeat(10,5))
print(np.full(10,5))

a = np.array([10,20,30])
print(np.repeat(a, 3))

<built-in function zeros>
<function ones at 0x00000224C58C9CA0>
[10 10 10 10 10]
[5 5 5 5 5 5 5 5 5 5]
[10 10 10 20 20 20 30 30 30]


np.full np.repeat'in tersi  
liste olursa unique'leri alır.  

10-20-30 yazdıran ödev istiyor. 3 kez 10 20 30 yazdırcan


In [32]:
print(np.repeat(10,5))
print(np.full(10,5))
print(np.full(3,a))

[10 10 10 10 10]
[5 5 5 5 5 5 5 5 5 5]
[10 20 30]


In [33]:
print(np.full(a,3))
print(len(np.full(a,3)))

agabunedir = np.full(a,3)
print(agabunedir[3])
print(agabunedir[3][1])
print(len(agabunedir[3][1]))


[[[3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  ...
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]]

 [[3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  ...
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]]

 [[3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  ...
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]]

 ...

 [[3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  ...
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]]

 [[3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  ...
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]]

 [[3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  ...
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]
  [3 3 3 ... 3 3 3]]]
10
[[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 

In [34]:

p2 = np.arange(0,100,10)
print(p2)
p3 = np.put(p2, [0,3,5], [19, 42, 45])
print(p2)
print(p3)

[ 0 10 20 30 40 50 60 70 80 90]
[19 10 20 42 40 45 60 70 80 90]
None


In [35]:
import re 
###
# mail validity check eden fonksiyon yazacağız. total 8 rakam olmalı, ilk rakam 1,8,9 olmalı. 
###
def phone_validator(tel_no):
    pass

ornek_no = '100000000'

pattern = r'([189][0-9])'
pattern2 = r'(^[189][0-9]{8,8})'

pattern2 = r'((1|8|9)([0-9]{7})$)'

print(re.search(pattern2, str(ornek_no)))

match = re.search(pattern2, str(ornek_no))

if match:
    print('valid')
else:
    print('invalid')



None
invalid


In [36]:
my_matrix = np.array([[6,7,8,9],[10,20,30,40], [51, 61, np.nan, 81], [112, 122, 132, np.nan], [np.nan, 3123, 3133, 3143]])
print(my_matrix)

[[   6.    7.    8.    9.]
 [  10.   20.   30.   40.]
 [  51.   61.   nan   81.]
 [ 112.  122.  132.   nan]
 [  nan 3123. 3133. 3143.]]


In [37]:
np.isnan(my_matrix)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [ True, False, False, False]])

In [38]:
np.where(np.isnan(my_matrix))

(array([2, 3, 4], dtype=int64), array([2, 3, 0], dtype=int64))

### NP WHERE'DE SAYARKEN ILK ARRAY SATIR BAZLI, HANGI SATIRDA NAN VAR KONTROL EDIYOR. IKINCI ARRAY SUTUN BAZLI, ELEMENTLERIN ARRAYDEKI INDEKSINI DONUYOR. 
Ilk true 3. satırda ama bu bilgiyi mevcut dönütlerde göremeyiz. 2. arraydeki sıralama ilk true'dan başlıyor. Peki 2 true olsa ne yapardı?

In [39]:
my_matrix = np.array([
    [6,7,8,9],
    [10,20,30,40],
    [51, np.nan, np.nan, 81],
    [112, 122, 132, np.nan],
    [np.nan, 3123, 3133, 3143]
    ])
print(my_matrix)
print(np.where(np.isnan(my_matrix)))
np.isnan(my_matrix)

[[   6.    7.    8.    9.]
 [  10.   20.   30.   40.]
 [  51.   nan   nan   81.]
 [ 112.  122.  132.   nan]
 [  nan 3123. 3133. 3143.]]
(array([2, 2, 3, 4], dtype=int64), array([1, 2, 3, 0], dtype=int64))


array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False,  True],
       [ True, False, False, False]])

vov ilginç. matrisi açıp, tek boyuta indirip düz sayıyor galiba.

In [40]:
my_matrix = np.array([
    [6,7,8,9],
    [10,20,30,40],
    [51, np.nan, np.nan, 81],
    [112, 122, 132, np.nan],
    [np.nan, 3123, 3133, 3143]
    ])
print(my_matrix)
print(np.where(np.isnan(my_matrix)))
np.isnan(my_matrix)

[[   6.    7.    8.    9.]
 [  10.   20.   30.   40.]
 [  51.   nan   nan   81.]
 [ 112.  122.  132.   nan]
 [  nan 3123. 3133. 3143.]]
(array([2, 2, 3, 4], dtype=int64), array([1, 2, 3, 0], dtype=int64))


array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True, False],
       [False, False, False,  True],
       [ True, False, False, False]])

In [2]:
import numpy as np 
nparray_1 = np.array([10,20,30,40,50,60,70,80,90])
print(type(np.isin(nparray_1, 10)))
print(np.isin(nparray_1, 10))
print(nparray_1[np.isin(nparray_1, 10)])

<class 'numpy.ndarray'>
[ True False False False False False False False False]
[10]


In [42]:
nparray_2 = np.arange(10,30,1)
print(nparray_2)
print(nparray_2[::-1])
print(np.flip(nparray_2))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [14]:
nparray_3 = np.array([[20,30,10],[35,3,8],[-100, -200, -300]])
nparray_3

array([[  20,   30,   10],
       [  35,    3,    8],
       [-100, -200, -300]])

In [6]:
nparray_3_2 = np.sort(nparray_3, axis=1)
nparray_3_2

array([[ 10,  20,  30],
       [  3,   5,   8],
       [100, 200, 300]])

In [13]:
nparray_3_3 = np.sort(nparray_3, axis=0)
nparray_3_3

array([[-100, -200, -300],
       [  20,    3,    8],
       [  35,   30,   10]])

In [46]:
import numpy as np 
c1 = np.array([10, 20, 30])
c2 = np.array([12, 20, 33])
print([c1,c2])
print('Stack Types, Horizontal:',np.hstack([c1,c2]))
print('Stack Types, Vertical:',np.vstack([c1,c2]))


[array([10, 20, 30]), array([12, 20, 33])]
Stack Types, Horizontal: [10 20 30 12 20 33]
Stack Types, Vertical: [[10 20 30]
 [12 20 33]]


### subarraylar farklı data tipinde olabiliyor.

In [47]:
c1 = np.array([10, 20, 30])
c2 = np.array(['ab', 'cd', 'ef'])
print([c1,c2])
print('Stack Types, Horizontal:',np.hstack([c1,c2]))
print('Stack Types, Vertical:',np.vstack([c1,c2]))

[array([10, 20, 30]), array(['ab', 'cd', 'ef'], dtype='<U2')]
Stack Types, Horizontal: ['10' '20' '30' 'ab' 'cd' 'ef']
Stack Types, Vertical: [['10' '20' '30']
 ['ab' 'cd' 'ef']]


Matris çarpımı == dot

In [48]:
x = np.array([[1,0,4],[3,3,1]])
y = np.array([[2,5],[1,1],[3,2]])
x.dot(y)
"""
1 0 4    2 5      
3 3 1    1 1     
         3 2
"""

'\n1 0 4    2 5      \n3 3 1    1 1     \n         3 2\n'

In [49]:
x = np.array([[1,2,3],[4,5,6]])
print("We've just created a ", type(x))

print("Our template has shape as", x.shape)
print("Total size is", x.size)
print("Item size is", x.itemsize)
print("The dimension of our array is", x.ndim)
print("Data type of elements are", x.dtype)
print("It consumes", x.nbytes, "bytes")
x = np.array(x, dtype=np.int64)
print("Now = Int64 consumes", x.nbytes, "bytes")

We've just created a  <class 'numpy.ndarray'>
Our template has shape as (2, 3)
Total size is 6
Item size is 4
The dimension of our array is 2
Data type of elements are int32
It consumes 24 bytes
Now = Int64 consumes 48 bytes


In [50]:
#Array operasyonları
my_list = [2, 14, 6, 8]
my_array = np.asarray(my_list)
my_array

array([ 2, 14,  6,  8])

In [51]:
second_array = np.zeros(4) + 3
second_array

array([3., 3., 3., 3.])

In [52]:
third_array = np.identity(4)
third_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

repeat dersen her itemı 3 kere olusturur oyle ilerler

In [53]:
a = np.array([10,20,30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [54]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [55]:
np.repeat(5,10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [56]:
from timeit import default_timer as timer
import random 
from random import getrandbits
list_form = list()
array_form = np.array(1, dtype=np.int32)
for i in range(100000):
    #my_random = random.choice([True, False])
    my_random = random.choice(range(3000))
    list_form.append(my_random)
    array_form = np.append(array_form, my_random)
array_form = array_form[1:]

test_array = np.arange(100000) + 10000
# test_array = test_array.astype(float)
# print(test_array)
# print(list_form[:10])
# print(array_form)
# print(len(array_form))
start = timer()
array_result = test_array[array_form % 2 == True]
end = timer()
array_diff = end - start

start = timer()
list_result = test_array[[i % 2 for i in list_form] == True]
end = timer()
list_diff = end - start



print(list_diff)
print(array_diff)
print(array_diff / list_diff)
print(array_diff > list_diff)



0.008389399998122826
0.0011875000054715201
0.1415476679783095
False


In [57]:
array_form = np.array(None, dtype=np.int32)


TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [ ]:
array_form = np.array(None, dtype=bool)
array_form


array(False)

In [ ]:
a = np.array([10,20,30])[1:]
a

array([20, 30])

In [ ]:
list_form = [1,2,3,4,5]
[i % 2 for i in list_form]


[1, 0, 1, 0, 1]

## aralıga gore sayi olusturma
### LINSPACE | LOGSPACE | GEOSPACE


In [ ]:
x_lin = np.linspace(1, 81, num = 21)
print(x_lin)
x_log = np.logspace(1, 4, num = 4)
print(x_log)
x_geo = np.geomspace(1,625, num=5)
print(x_geo)

[ 1.  5.  9. 13. 17. 21. 25. 29. 33. 37. 41. 45. 49. 53. 57. 61. 65. 69.
 73. 77. 81.]
[   10.   100.  1000. 10000.]
[  1.   5.  25. 125. 625.]


In [ ]:
x = np.logspace(0, 1, num = 3)
x

array([ 1.        ,  3.16227766, 10.        ])

In [ ]:
x = np.logspace(np.log10(1), np.log10(4), num = 3)
x

array([1., 2., 4.])

In [ ]:
expp = np.log10(4)
newbase_exp = np.log(4) / (np.log(3) * expp)
newbase_exp


2.0959032742893844

In [ ]:
np.log(4)

1.3862943611198906

In [ ]:
np.log(3)

1.0986122886681098

ARRAY JOIN OPERASYONLARI

In [ ]:
c1 = np.array([10, 20, 30, 40, 50, 60])
c2 = np.array([12, 20, 33, 40, 55, 60])

In [ ]:
np.intersect1d(c1, c2)

array([20, 40, 60])

In [ ]:
np.setdiff1d(c1, c2)

array([10, 30, 50])

## WHERE cok kritik ve cok güzel bi fonksiyon

In [ ]:
a = np.array([1,2,3,6,8])
b = np.array([10,2,30,60,8])
print(np.where(a == b))
print(a[np.where(a == b)])

(array([1, 4], dtype=int64),)
[2 8]


In [ ]:
import numpy as np 
a1 = np.arange(0, 60)
a1[np.where ((a1 > 20) & (a1 < 35))]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [ ]:
a1[np.where (((a1 > 20) & (a1 < 28)) | (a1 % 10 == 0))]

array([ 0, 10, 20, 21, 22, 23, 24, 25, 26, 27, 30, 40, 50])

In [ ]:
np.logical_and(a1 > 20, a1 < 28)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
a1[np.logical_and(a1 > 20, a1 < 28)]

array([21, 22, 23, 24, 25, 26, 27])

In [ ]:
np.isin(a1, [20,28])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
np.isin(a1, [range(20,28)])

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
a3 = np.array([[3,2,8,1], [70,50,10,67], [45,25,75,15]])
a3

array([[ 3,  2,  8,  1],
       [70, 50, 10, 67],
       [45, 25, 75, 15]])

In [ ]:
np.sort(a3)

array([[ 1,  2,  3,  8],
       [10, 50, 67, 70],
       [15, 25, 45, 75]])

In [ ]:
np.sort(a3, axis=0)

array([[ 3,  2,  8,  1],
       [45, 25, 10, 15],
       [70, 50, 75, 67]])

In [ ]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

dotp = a1@a2
print("Dotp - ", dotp)

dotp = np.dot(a1, a2)
print("Dotp using np.dot - ", dotp)

dotp = np.inner(a1, a2)
print("Dotp using np.inner - ", dotp)

dotp = sum(np.multiply(a1, a2))
print("Dotp using np.multiply & sum - ", dotp)

dotp = np.matmul(a1, a2)
print("Dotp using np.matmul - ", dotp)

dotp = 0
for i in range(len(a1)):
    dotp = dotp + a1[i]*a2[i]
print("Dotp using for loop - ", dotp)

Dotp -  32
Dotp using np.dot -  32
Dotp using np.inner -  32
Dotp using np.multiply & sum -  32
Dotp using np.matmul -  32
Dotp using for loop -  32


Normalizasyonnnnnnnnn

In [ ]:
v1 = [2, 3]
length_v1 = np.sqrt(np.dot(v1,v1))
norm_v1 = v1 / length_v1
length_v1 , norm_v1

(3.605551275463989, array([0.5547002 , 0.83205029]))

In [ ]:
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [ ]:
M = np.random.randn(6, 5)
print(M)

[[-0.10722378 -0.52682304 -0.35450337 -0.16183204  0.35556314]
 [ 1.00005421 -0.01319602  0.03283378  0.23228745 -0.99720975]
 [ 0.29830557  0.24991174  0.07332124 -0.81094565  0.29070836]
 [ 0.2949985   0.04294709  1.18166343 -2.54606703 -1.53350518]
 [ 0.65213984 -0.83656642 -0.97606628 -0.5719696   2.40684523]
 [ 1.23712932 -0.14031267  0.66758045 -0.08976631 -0.68474689]]


In [ ]:
M = np.random.randn(5, 1)
print(M)

[[-1.1950317 ]
 [ 1.0158307 ]
 [-0.31228233]
 [ 0.98871232]
 [ 0.17917186]]


In [ ]:
np.random.uniform(10, 20, size = (5,5))

array([[16.19469743, 16.66661903, 19.73271959, 10.02064278, 18.05307788],
       [19.22587179, 19.32059516, 16.36503249, 11.21785682, 12.07032982],
       [11.16131999, 17.20566879, 18.41324967, 18.65814292, 10.86263213],
       [18.41524834, 17.08961959, 19.69335593, 11.89038482, 11.71763242],
       [12.86058477, 16.51467861, 17.64521578, 19.51898734, 17.42224416]])

In [ ]:
np.random.uniform(10, 20, size = (3,7))

array([[15.93618892, 14.87092618, 17.63067571, 11.41099677, 12.6048869 ,
        13.18180878, 19.67667511],
       [17.18271966, 17.40219074, 12.18380125, 19.54133729, 19.01655059,
        10.50075338, 16.28689397],
       [12.75598261, 11.11003668, 12.17428021, 14.00527695, 16.94544943,
        12.9131918 , 18.42660946]])

In [ ]:
A = np.arange(1,17).reshape(4,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

a.ravel():  
(i) Return only reference/view of original array  
(ii) If you modify the array you would notice that the value of original array also changes.  
(iii) Ravel is faster than flatten() as it does not occupy any memory.  
(iv) Ravel is a library-level function.  

a.flatten() :  
(i) Return copy of original array  
(ii) If you modify any value of this array value of original array is not affected.  
(iii) Flatten() is comparatively slower than ravel() as it occupies memory.  
(iv) Flatten is a method of an ndarray object. 


In [ ]:
A.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
A.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
# Python code to differentiate
# between flatten and ravel in numpy
import numpy as np
  
# Create a numpy array
a = np.array([(1,2,3,4),(3,1,4,2)])
  
# Let's print the array a
print ("Original array:\n ") 
print(a)
  
# To check the dimension of array (dimension =2)
# ( and type is numpy.ndarray )
print ("Dimension of array-> " , (a.ndim))
  
  
print("\nOutput for RAVEL \n") 
# Convert nd array to 1D array
b = a.ravel()
  
# Ravel only passes a view of 
# original array to array 'b'
print(b)
b[0]=1000
print(b)
  
# Note here that value of original
# array 'a' at also a[0][0] becomes 1000
print(a)
  
# Just to check the dimension i.e. 1
# (and type is same numpy.ndarray )
print ("Dimension of array->" ,(b.ndim))
  
print("\nOutput for FLATTEN \n") 
  
# Convert nd array to 1D array
c = a.flatten()
  
# Flatten passes copy of
# original array to 'c'
print(c)
c[0]=0
print(c)
  
# Note that by changing
# value of c there is no
# affect on value of original
# array 'a'
print(a)
  
print ("Dimension of array-> " , (c.ndim))

Original array:
 
[[1 2 3 4]
 [3 1 4 2]]
Dimension of array->  2

Output for RAVEL 

[1 2 3 4 3 1 4 2]
[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array-> 1

Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array->  1


In [ ]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
N = np.array([[1,1,1], [2,2,2], [3,3,3]])

C = M + N
print(C)

#OR

C = np.add(M, N, dtype = np.float64)
print(C)

[[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]
[[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


In [ ]:
C = M - N
print(C)
C = np.subtract(M, N, dtype = np.float64)
print(C)

[[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]
[[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


In [ ]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])

print(np.transpose(M))

print('sameee')
#OR

print(M.T)

[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]
sameee
[[ 1  4  7]
 [ 2 -3  8]
 [ 3  6  0]]


In [ ]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])

print(np.linalg.det(M))

195.0


In [ ]:
print(np.linalg.inv(M))

[[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


In [ ]:
M = np.array([[1,2,3], [4,-3,6], [7,8,0]])
N = np.array([[1,1,1], [2,2,2], [3,3,3]])

print("\n Matrix Division (M/N) ==> \n ", M/N)

#OR

print("\n Matrix Division (M/N) ==> \n ", np.divide(M,N))


 Matrix Division (M/N) ==> 
  [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]

 Matrix Division (M/N) ==> 
  [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


In [ ]:
M1 = np.array([[1,2], [4,5]])
M1

array([[1, 2],
       [4, 5]])

In [ ]:
M1@M1@M1

array([[ 57,  78],
       [156, 213]])

In [ ]:
np.linalg.matrix_power(M1, 3)

array([[ 57,  78],
       [156, 213]])

In [ ]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([[1,1], [1,1]])

C = np.concatenate((A,B))
C

array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [1, 1]])

In [ ]:
x = np.array([0, 1, 0, 0])
y = np.array([1, 1, 0, 1])
z = np.logical_or(x,y)
z

array([ True,  True, False,  True])

## R_ ve C_ ile axisler üzerinden arrayler birlestirme!!!!!


In [ ]:
a = np.array([[1,2,3],
             [11,22,33]]
             )
b = np.array([[4,5,6],
             [44,55,66]]
             )

first_axis_combine = np.r_[a,b] #along rows
second_axis_combine = np.c_[a,b] #along columns

print(first_axis_combine)

print('--------------\n Second Axis yani sütunlari birlestirme')

print(second_axis_combine)


[[ 1  2  3]
 [11 22 33]
 [ 4  5  6]
 [44 55 66]]
--------------
 Second Axis yani sütunlari birlestirme
[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [ ]:
a = np.array([[1,2,3],
             [11,22,33]]
             )
b = np.array([[4,5,6,7],
             [44,55,66,77]]
             )

#first_axis_combine = np.r_[a,b] #along rows
second_axis_combine = np.c_[a,b] #along columns
print(second_axis_combine)

[[ 1  2  3  4  5  6  7]
 [11 22 33 44 55 66 77]]


### Load text ile basit dosyalari isleme  

- dtype = str fln dikkat
- skiprows var
- evet
 

In [ ]:
# Assign filename: file
file = 'seaslug.txt'

# Import file: data
data = np.loadtxt(file, delimiter='\t', dtype=str)

# Print the first element of data
print(data[0])

# Import data as floats and skip the first row: data_float
data_float = np.loadtxt(file, delimiter='\t', dtype=float, skiprows=1)

# Print the 10th element of data_float
print(data_float[9])

# Plot a scatterplot of the data
plt.scatter(data_float[:, 0], data_float[:, 1])
plt.xlabel('time (min.)')
plt.ylabel('percentage of larvae')
plt.show()

The function np.loadtxt() will freak at this. There is another function, np.genfromtxt(), which can handle such structures. If we pass dtype=None to it, it will figure out what types each column should be.  
++ bir de recfromcsv var, defaultları üstteki gibi. 

In [ ]:
data = np.genfromtxt('titanic.csv', delimiter=',', names=True, dtype=None)
d = np.recfromcsv(file)

data framede de böyle bisi var. comment ne, na_values nothing ney

In [ ]:
# Import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

# Assign filename: file
file = 'titanic_corrupt.txt'

# Import file: data
data = pd.read_csv(file, sep='\t', comment='#', na_values='Nothing')

# Print the head of the DataFrame
print(data.head())

# Plot 'Age' variable in a histogram
pd.DataFrame.hist(data[['Age']])
plt.xlabel('Age (years)')
plt.ylabel('count')
plt.show()


Klasik data tipleri için np ve df okey ama çeşitlenince yetersiz oluyor. Json için dict ok. Farklı data tiplerini storelamak icin pythonın unique çözümü pickle. Binary halinde tutuyor veriyi. Human readable olmak zorunda değil.

In [15]:
import os
wd = os.getcwd()
os.listdir(wd)

['.ipynb_checkpoints',
 '.vscode',
 '0061892.py',
 '0061892_old.py',
 '006_laylay.py',
 '10-neptune_98589.ico',
 '1804_yavuzhanyavuz_case.ipynb',
 '2048.py',
 'aaaa.py',
 'AAAAAAAAAAAAAAA.py',
 'amk_input.txt',
 'ayy.py',
 'basics_datatypes.ipynb',
 'bc_28-30052022 - AIUP.ipynb',
 'bilira.py',
 'Bootcamp_datas',
 'corluhan.ipynb',
 'dataframe.ipynb',
 'debug_1304.py',
 'eski_0061892.py',
 'from sklearn.metrics import r2_score.py',
 'helloflask.py',
 'hw02.ipynb',
 'hw02_random-variate_generation_template(1).ipynb',
 'hw03_input_modeling_template - Copy.ipynb',
 'hw03_input_modeling_template.ipynb',
 'HW2_data.xlsx',
 'hw4.ipynb',
 'hw5.ipynb',
 'hw5_deneme.ipynb',
 'hw6.ipynb',
 'id_list.txt',
 'indr372.html',
 'indr372.ipynb',
 'indr372.pdf',
 'indr372.py',
 'indr372_part2.ipynb',
 'indr372_part2.py',
 'joins.ipynb',
 'junk',
 'logic.py',
 'machinelearning_study.ipynb',
 'newdriverslicence_case2.ipynb',
 'notifs.py',
 'notifs_task.bat',
 'notify_messages.csv',
 'numpy_operations.ipynb

### EXCELDE SHEET OKUMAAAAAAAAA

In [ ]:
xls = pd.ExcelFile('battledeath.xlsx')
print(xls.sheet_names)

df1 = xls.parse('2004') ## ISIM ILE SHEET CEKME
df2 = xls.parse(1) ## INDEX ILE SHEET CEKME

Terabaytlık veriler için (özellikle numerical ise) HDF5 kullanılıyor